services:
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-mlflow_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mlflow_password}
      POSTGRES_DB: ${POSTGRES_DB:-mlflow_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mlops-network

  mlflow-server:
    build: 
      context: .
      dockerfile: docker/mlflow.Dockerfile
    container_name: mlflow-tracking-server
    restart: always
    ports:
      - "5000:5000"
    command: >
      mlflow server --backend-store-uri postgresql://${POSTGRES_USER:-mlflow_user}:${POSTGRES_PASSWORD:-mlflow_password}@db:5432/${POSTGRES_DB:-mlflow_db} --default-artifact-root mlflow-artifacts:/ --host 0.0.0.0 --port 5000 --allowed-hosts "*"
    volumes:
      - mlartifacts_data:/mlartifacts
    networks:
      - mlops-network
    depends_on:
      - db

  api-service:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    restart: always
    ports:
      - "8000-8002:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow-server:5000
      - MODEL_NAME=Gold_Price_Predictor
      - MODEL_STAGE=Production
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-dummy}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-dummy}
    volumes:
      - mlartifacts_data:/mlartifacts
    deploy:
      replicas: 3
    networks:
      - mlops-network
    depends_on:
      - mlflow-server

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - mlops-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - mlops-network
    depends_on:
      - api-service
      - cadvisor

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - mlops-network
    depends_on:
      - prometheus

networks:
  mlops-network:
    driver: bridge

volumes:
  postgres_data:
  mlartifacts_data: