global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'gold_prediction_api'
    static_configs:
      - targets: ['api-service:8000']
        
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']